### ISSUE TITLE
Feedback for Group 19

### ISSUE THREAD

**Issue by nichowu** [UBC-MDS/DSCI_532_Group18_Allstars-R#2]
Leave your feedback for Group 19 in this issue.

**Comment by williamxu7** [comment]
We are HR professionals in a tech company. We would like to see some statistics on the mental health of tech workers around the world in order to get some ideas to set some good HR policies in our organization.

Three things we like about your dashboard:
- All Altair plots are clear and nice
- The layout is good and easy for us to navigate
- The pie charts are extremely cool and gives us some insights on employee mental health information across the globe

Three things for potential improvement:
- Maybe it can be useful to include a short description in the overview section
- The colors of countries in the pie chart. For example, UK has different colors. Maybe it would be better to have one color represent each country across all three pies. (We know pie charts are hard to make, so if this adjustment is time-consuming, do not worry about it :D )
- Maybe a very short intro of the app on top

Overall, this dashboard is pretty awesome, we enjoy using it. Great job! Now we know how to update our HR policies to make the company great again!
